### ISSUE TITLE
Compatibility with bwa-aln

### ISSUE THREAD

**Issue by bknisbac** [ferrannadeu/IgCaller#1]
Hi Ferran, 
Would be great if you could add compatibility with bwa-aln, as we discussed. 

Thanks,
Binyamin

**Comment by ferrannadeu** [comment]
Hi Binyamin,

I have slightly adjusted the code so it now works better with bam files obtained using bwa-aln. You could download and run again IgCaller on your bwa-aln bam files and you should get more rearrangements than before. Nonetheless, the number of rearrangements that can be reconstructed by IgCaller is higher in bwa-mem than in bwa-aln bam files from the same sample (around 20 samples analyzed with both bwa-mem and bwa-aln bam files). Bwa-aln does not report split (ie chimeric) reads as bwa-mem does and although some of these reads can be recovered by IgCaller, not all of them are. This fact impairs the proper reconstruction of some rearrangements using bwa-aln bam files. Besides, some rearrangements are identified with a lower number of reads supporting the rearrangement, which does not help distinguishing true rearrangements from likely artifacts in some cases. Also, the “noise” in the IgCaller results seems to increase with bwa-aln due to the lack of split reads in the original bwa-aln bam file and the way IgCaller try to recover them. Overall, in order to have more robust, complete, and validated results using IgCaller I would recommend you realigning the bam files using bwa-mem. To speed up this process, you could just extract the reads in which one read-pair maps to the IG loci (hg19: 14:106052774-107288051 22:22380000-23264000 2:89131589-90274600 ; or hg38: 14:105583730-106879900 22:22025700-22921700 2:88832000-90235600) and realign them using bwa-mem. I would also like to mention that we have only used bam files obtained using bwa-mem in our benchmark and doing a proper validation of IgCaller with bwa-aln in a large cohort of WGS is not in our top priority in a short term.

Let me know if I can be of further help!

Thanks,

Ferran
