### ISSUE TITLE
Error in getDsequence

### ISSUE THREAD

**Issue by pblaney** [ferrannadeu/IgCaller#5]
Hello Ferran,

Very impressive and useful tool! I am trying to implement its use and while it was successfully executed for the vast majority of samples in my input, there was a recurring error for a subset.
Below is the code snippet that was run for the WGS matched T/N pairs originating from multiple myeloma patients:

```
python3 IgCaller.py \
--inputsFolder IgCaller_reference_files/ \
--genomeVersion hg38 \
--chromosomeAnnotation ucsc \
--bamN sampleX_N.bam \
--bamT sampleX_T.bam \
--refGenome Homo_sapiens_assembly38.fasta \
--outputPath . \
-@ 2
```

Here is the error message that was output from this run:

```
IgCaller: checking inputs and outputs...
IgCaller: creating IG mini BAM files...
[W::hts_idx_load2] The index file is older than the data file: sampleX_T.bam.bai
[W::hts_idx_load2] The index file is older than the data file: sampleX_N.bam.bai
IgCaller: IGH...
[mpileup] 1 samples in 1 input files
....
....
[mpileup] 1 samples in 1 input files
Traceback (most recent call last):
  File "/home/toolshed/IgCaller/IgCaller.py", line 291, in <module>
    information = getDsequence(information, annot_table_JV, GENE, Dseqs)
  File "/home/toolshed/IgCaller/IgCaller_reference_files/IgCaller_functions.py", line 1111, in getDsequence
    if min([count for count, item in enumerate(cigar1) if "M" in item]) < min([count for count, item in enumerate(cigar1) if "S" in item]):
ValueError: min() arg is an empty sequence
```

From my very basic troubleshooting it appears the `cigar1` variable is empty but I am not sure if this is for the "M" or "S" count.
For some background, the BAMs were aligned with BWA MEM v0.7.17 and I am using IgCaller.py v1.2.
As I said in the beginning, other samples that were preprocessed in the same manner ran through IgCaller without a problem so I am unsure why this error is unique to a select few.

Let me know if you need more details.
Best,
Patrick

**Comment by ferrannadeu** [comment]
Hello Patrick,

Thank you for your message!

It's strange; I never got this error. Could you share with me one pair of tumor and normal mini bam files that are generated by IgCaller just at the begining of the execution so I could more easily try to solve the problem? If these mini bam files are not kept after the error, you could run one of these problematic pair of samples using the "--keepMiniIgBams yes".

Here my email in case you prefer to share them privately: nadeu@clinic.cat

Thanks in advance,

Ferran

**Comment by pblaney** [comment]
Ferran,

Thank you for getting back to me on this issue. I have rerun the use case to be sure it was reproducible and I still had the same error. I will follow up and email you the created mini BAM files.

Patrick

**Comment by ferrannadeu** [comment]
Thanks for sharing the mini BAMs!

This issue was related to the annotation of "spit-reads" that IgCaller uses internally, which was incompatible/not accurate when working with BAM files aligned against a reference genome including the "alt" contigs. It only effected a subset of samples because I guess those samples are the ones that have an IG rearrangement (either true or noise) involving reads that can align to both the "main chromosome" (i.e., chr14) and to an "alt" contig (chr14_KI270846v1_alt, for example).

I have updated the code in the master-branch (v1.2.1). It works well for the case that you have shared with me.

I do not expect that the results of those samples that finished correctly using the previous v1.2 will change if you re-run them using v1.2.1.

Please, let me know if it solves the problem for all the remaining samples. Thanks in advance!!

Ferran

**Comment by pblaney** [comment]
Hi Ferran,

After updating to the most recent update (commit `56d2cd03f9ab7613bceba04265aa5b982dde2d17` ~ v1.2.1) and rerunning the code snippet above, I received no error and the results were comparable to other samples without this error.

Closing the issue, many thanks Ferran
